### ISSUE TITLE
最新章节不能翻页

### ISSUE THREAD

**Issue by xu-li-logic** [kagaricyan/legado-web-for-kindle#1]
阅读完一本书的最新章节（例如第11章）以后，点击下一章会出现空白页面。

当该书有更新的章节（例如第12章）以后，则无法阅读更新的章节（第12章）。kindle只会显示第12章的第一页文字，没有第12章的标题且无法翻页。

**Comment by kagaricyan** [comment]
感谢反馈，已修复。
新增手动同步：
![image](https://github.com/user-attachments/assets/ea6662f6-de67-4937-9b2a-a91b2edeffd8)

另外新章节标题(例如12章),在未获取到前，可能展示是章节数对不上，同步后会对上。
比如书源1-11章每一章都重复了一次，那么“第12章”会显示成第23章(前面有22个章节，未同步前，顺推到第23)，点击同步后，会自动变成“第12章”

**Comment by kagaricyan** [comment]
> 阅读完一本书的最新章节（例如第11章）以后，点击下一章会出现空白页面。
> 
> 当该书有更新的章节（例如第12章）以后，则无法阅读更新的章节（第12章）。kindle只会显示第12章的第一页文字，没有第12章的标题且无法翻页。

已更新，参考readme替换一下页面

**Comment by xu-li-logic** [comment]
非常感谢修复这个bug！在我见过的类似的项目中，这是最好的。
